// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5OuPOQ_PcSQhbvjtgBiouNocospLPS6Q',
    appId: '1:92798913031:web:7c2a492ffd48105e57f8a2',
    messagingSenderId: '92798913031',
    projectId: 'bunbun-mart',
    authDomain: 'bunbun-mart.firebaseapp.com',
    storageBucket: 'bunbun-mart.firebasestorage.app',
    measurementId: 'G-0W15J7WFPJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp5N74vmMDwXVdb_qhKPhBh_AqOqtNWT0',
    appId: '1:92798913031:android:0ffa37cc453ba6fb57f8a2',
    messagingSenderId: '92798913031',
    projectId: 'bunbun-mart',
    storageBucket: 'bunbun-mart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1wMeDmK0NLZkRZjHbSSxZTRhMx7GuALA',
    appId: '1:92798913031:ios:e7eda69f9efcf79d57f8a2',
    messagingSenderId: '92798913031',
    projectId: 'bunbun-mart',
    storageBucket: 'bunbun-mart.firebasestorage.app',
    androidClientId: '92798913031-n0mi360hp8f3hhloqu5avi2t08qcb403.apps.googleusercontent.com',
    iosClientId: '92798913031-pgs7rklqhmv1ip8mdhk8c29fbkrca0gl.apps.googleusercontent.com',
    iosBundleId: 'com.example.bunbunmart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5OuPOQ_PcSQhbvjtgBiouNocospLPS6Q',
    appId: '1:92798913031:web:ff0e8a6da9ea5c0f57f8a2',
    messagingSenderId: '92798913031',
    projectId: 'bunbun-mart',
    authDomain: 'bunbun-mart.firebaseapp.com',
    storageBucket: 'bunbun-mart.firebasestorage.app',
    measurementId: 'G-0QK4ZBZPKV',
  );

}